# python -m pip install pre-commit
# pre-commit install --config .githooks.yml
# pre-commit install --config .githooks.yml --hook-type commit-msg

default_stages: [commit]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/pycqa/pylint
    rev: v2.8.3
    hooks:
      - id: pylint
        args:
          - --rcfile=.pylintrc
        language_version: python3
        exclude: (^migrations, | ^frontend)

  - repo: https://github.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        args: ['--ignore=E203, E501, E126',"--max-line-length=120"]
        language_version: python3
        exclude: (^migrations, | ^frontend)

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
      - id: mypy
        additional_dependencies: [types-all]
        exclude: (^migrations, | ^frontend)
        language_version: python3

  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.15.1
    hooks:
      - id: gitlint
